### ISSUE TITLE
[Error] Parsing solidity version in a range

### ISSUE THREAD

**Issue by thanhtoantnt** [taquangtrung/solc-detect#2]
- Example: `pragma solidity >=0.4.21 < 0.6.0;`
- Error: `ValueError: Invalid NPM block in '>=0.4.21 < 0.6.0': '<'`

**Comment by taquangtrung** [comment]
It's a bug of [python-semanticversion](https://github.com/rbarrois/python-semanticversion/).

It doesn't allow whitespace between `<` and `0.6.0`.

@thanhtoantnt: can you fix the bug on the benchmark first?

We can fix on `solc-detect` or raise an issue to `node-semver` later.

**Comment by thanhtoantnt** [comment]
@taquangtrung you mean to change the `pragma` in the test case if it has the solidity version like this?

**Comment by taquangtrung** [comment]
Yes, we can temporarily fix the benchmark to: `pragma solidity >=0.4.21 <0.6.0;`

This is an incompatibility between the semantic versioning of Solc and Nodejs.

**Comment by taquangtrung** [comment]
The issue with whitespace was discussed here: https://github.com/rbarrois/python-semanticversion/issues/127

But it seems the author's response is slow.

**Comment by taquangtrung** [comment]
@thanhtoantnt: you shouldn't close this issue, since we haven't fixed it in this repo.

**Comment by taquangtrung** [comment]
Anyway, I just fixed it in this commit: https://github.com/taquangtrung/solc-detect/commit/e74324beb793368f81c68f7c003244ace913c5f5

So now it can be closed
